// Build a .env string for a chosen environment, entirely client-side.

import type { VaultService } from './types';

export function generateEnv(
  services: VaultService[],
  environment: string,
  selectedIds?: string[],
): string {
  const chosen = selectedIds ? services.filter((s) => selectedIds.includes(s.id)) : services;

  const blocks = chosen
    .map((service) => {
      const lines = service.fields
        .filter((f) => f.key.trim().length > 0 && f.values[environment] !== undefined)
        .map((f) => `${f.key}=${f.values[environment]}`);
      if (lines.length === 0) return '';
      return [`# ${service.name}`, ...lines].join('\n');
    })
    .filter((block) => block.length > 0);

  const header = [
    `# Generated by NovaBash, local-first. Environment: ${environment}.`,
    '# These values came from your on-device vault. Do not commit this file.',
    '',
  ].join('\n');

  return `${header}${blocks.join('\n\n')}\n`;
}

export function downloadEnv(content: string, filename = '.env'): void {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
