// Build a .env string from selected services, entirely client-side.

import type { VaultService } from './types';

export function generateEnv(services: VaultService[], selectedIds?: string[]): string {
  const chosen = selectedIds
    ? services.filter((s) => selectedIds.includes(s.id))
    : services;

  const blocks = chosen.map((service) => {
    const header = `# ${service.name}`;
    const lines = service.fields
      .filter((f) => f.key.trim().length > 0)
      .map((f) => `${f.key}=${f.value}`);
    return [header, ...lines].join('\n');
  });

  const header = [
    '# Generated by NovaBash, local-first.',
    '# These values came from your on-device vault. Do not commit this file.',
    '',
  ].join('\n');

  return `${header}${blocks.join('\n\n')}\n`;
}

export function downloadEnv(content: string, filename = '.env'): void {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
