-- NovaBash row-level security policies. Run after the Drizzle-generated
-- table migrations. These are not generated by drizzle-kit and live here
-- as a hand-managed migration.

alter table user_profile enable row level security;
alter table workspaces enable row level security;
alter table workspace_members enable row level security;
alter table environments enable row level security;
alter table credentials enable row level security;
alter table service_keys enable row level security;
alter table audit_log enable row level security;
alter table bundles_published enable row level security;

-- user_profile: each user owns exactly one row, identified by auth.uid().
create policy user_profile_self on user_profile
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- workspaces: visible to owner and members.
create policy workspaces_member_read on workspaces
  for select
  using (
    owner_id = auth.uid()
    or exists (
      select 1 from workspace_members wm
      where wm.workspace_id = workspaces.id and wm.user_id = auth.uid()
    )
  );

create policy workspaces_owner_write on workspaces
  for all
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

-- workspace_members: each user can read rows where they are the user_id.
create policy workspace_members_self_read on workspace_members
  for select
  using (user_id = auth.uid() or workspace_id in (select id from workspaces where owner_id = auth.uid()));

-- environments / credentials / service_keys / audit_log: gate by workspace ownership/membership.
create policy environments_via_workspace on environments
  for all
  using (
    workspace_id in (
      select id from workspaces where owner_id = auth.uid()
      union
      select workspace_id from workspace_members where user_id = auth.uid()
    )
  );

create policy credentials_via_environment on credentials
  for all
  using (
    environment_id in (
      select id from environments where workspace_id in (
        select id from workspaces where owner_id = auth.uid()
        union
        select workspace_id from workspace_members where user_id = auth.uid()
      )
    )
  );

create policy service_keys_via_workspace on service_keys
  for all
  using (
    workspace_id in (
      select id from workspaces where owner_id = auth.uid()
      union
      select workspace_id from workspace_members where user_id = auth.uid()
    )
  );

create policy audit_log_via_workspace on audit_log
  for select
  using (
    workspace_id in (
      select id from workspaces where owner_id = auth.uid()
      union
      select workspace_id from workspace_members where user_id = auth.uid()
    )
  );

-- bundles_published: public bundles readable by anyone signed in; private only by author.
create policy bundles_published_read on bundles_published
  for select
  using (is_public = true or author_user_id = auth.uid());

create policy bundles_published_author_write on bundles_published
  for all
  using (author_user_id = auth.uid())
  with check (author_user_id = auth.uid());
